// AUTO-GENERATED by scripts/generate-models.mjs — do not edit by hand.
// Model files use opaque hashed names (no descriptive filenames are shipped).
export const CAKE_MODEL_URL =
  import.meta.env.VITE_CAKE_MODEL_URL || '/models/cba3316d.glb';
